### ISSUE TITLE
AbortSignal.timeout is not a function

### ISSUE THREAD

**Issue by AzonInc** [jdalrymple/gitbeaker#3335]
**Description**

- Node.js version: 18.16.1
- Gitbeaker version: 39.4
- Gitbeaker release (cli, node, browser, core, requester-utils): node/rest
- OS & version: Windows 11

After updating from gitbeaker/node 35.7.0 to gitbeaker/rest 39.4.0 I'm experiencing the following error:
AbortSignal.timeout is not a function

**Steps to reproduce**

I use the following code to test it.
It used to work before the version change.

```
const gitlab_api = new Gitlab({
    host: store.gitlab_url,
    token: store.gitlab_api_token
});

let opts = {
    title: "title",
    description: "desc"
};

gitlab_api.Issues.create(store.gitlab_project_id, opts).then(resolve).catch(err => {
    console.log(err);
    reject(err);
});
```

**Expected behaviour**

**Actual behaviour**

**Possible fixes**

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Any chance you could put together a sample project so i could reproduce?

**Comment by AzonInc** [comment]
Okay my bad, I was using Electron 20 which is using Node 16 internally.
After updating Electron to v25 it's working fine.
